\copy aka_name from 'aka_name.csv' csv
\copy aka_title from 'aka_title.csv' csv
\copy cast_info from 'cast_info.csv' csv
\copy char_name from 'char_name.csv' csv
\copy comp_cast_type from 'comp_cast_type.csv' csv
\copy company_name from 'company_name.csv' csv
\copy company_type from 'company_type.csv' csv
\copy complete_cast from 'complete_cast.csv' csv
\copy info_type from 'info_type.csv' csv
\copy keyword from 'keyword.csv' csv
\copy kind_type from 'kind_type.csv' csv
\copy link_type from 'link_type.csv' csv
\copy movie_companies from 'movie_companies.csv' csv
\copy movie_info from 'movie_info.csv' csv
\copy movie_info_idx from 'movie_info_idx.csv' csv
\copy movie_keyword from 'movie_keyword.csv' csv
\copy movie_link from 'movie_link.csv' csv
\copy name from 'name.csv' csv
\copy person_info from 'person_info.csv' csv
\copy role_type from 'role_type.csv' csv
\copy title from 'title.csv' csv
